### ISSUE TITLE
Syntax error when attempting to install

### ISSUE THREAD

**Issue by quanterium** [lpirl/redmine_scm_hookhelpers#2]
I get a syntax error when attempting to install this plugin. Server is running CentOS 6.8. Any help would be appreciated.

```
Environment:
  Redmine version                2.6.3.stable
  Ruby version                   1.8.7-p374 (2013-06-27) [x86_64-linux]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               MySQL
```

```
$ sudo bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
SyntaxError: /var/www/redmine/plugins/redmine_scm_hookhelpers/lib/sys_controller_patch.rb:23: syntax error, unexpected ':', expecting ')'
...s = Repository.where(root_url: params[:root_url].to_s)
                              ^
/var/www/redmine/plugins/redmine_scm_hookhelpers/lib/sys_controller_patch.rb:23: syntax error, unexpected ')', expecting kEND
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:359:in `require_or_load'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:192:in `const_missing'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `each'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `const_missing'
/var/www/redmine/plugins/redmine_scm_hookhelpers/init.rb:14:in `_callback_before_89'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:473:in `_run__68434795__prepare__4__callbacks'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/lib/ruby/gems/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/usr/lib/ruby/gems/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/application/finisher.rb:47
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `send'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/redmine/config/environment.rb:14
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/lib/ruby/gems/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
/usr/lib/ruby/gems/1.8/gems/railties-3.2.21/lib/rails/application.rb:305:in `initialize_tasks'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by lpirl** [comment]
I am sorry to say that if you use a Redmine version that old, you're on your own.
If you can, try it with Redmine 3.x where it works for me.©
Feel free to create a pull request if you got it working for version 2.x and we can maintain those changes on a separate branch.
